import {
  Braces,
  Binary,
  Link2,
  FileText,
  AlignLeft,
  Palette,
  CaseSensitive,
  FileCode,
  KeyRound,
  Fingerprint,
  Clock,
  Minimize2,
  Code2,
  QrCode,
  Hash,
  ImageIcon,
  Type,
  PoundSterling,
  Receipt,
  Pipette,
  type LucideIcon,
} from "lucide-react";

export interface ToolMeta {
  slug: string;
  name: string;
  description: string;
  icon: LucideIcon;
  category: string;
  keywords: string[];
}

export const tools: ToolMeta[] = [
  {
    slug: "json-formatter",
    name: "JSON Formatter",
    description: "Format, validate and beautify JSON data with syntax highlighting.",
    icon: Braces,
    category: "Developer",
    keywords: ["json", "format", "validate", "beautify", "pretty print", "minify"],
  },
  {
    slug: "base64",
    name: "Base64 Encoder / Decoder",
    description: "Encode text to Base64 or decode Base64 back to plain text.",
    icon: Binary,
    category: "Encoding",
    keywords: ["base64", "encode", "decode", "binary", "text"],
  },
  {
    slug: "url-encoder",
    name: "URL Encoder / Decoder",
    description: "Encode or decode URLs and query string parameters.",
    icon: Link2,
    category: "Encoding",
    keywords: ["url", "encode", "decode", "percent", "uri", "query string"],
  },
  {
    slug: "word-counter",
    name: "Word & Character Counter",
    description: "Count words, characters, sentences and paragraphs in any text.",
    icon: FileText,
    category: "Text",
    keywords: ["word", "character", "count", "sentence", "paragraph", "length"],
  },
  {
    slug: "lorem-ipsum",
    name: "Lorem Ipsum Generator",
    description: "Generate placeholder text in paragraphs, sentences or words.",
    icon: AlignLeft,
    category: "Text",
    keywords: ["lorem", "ipsum", "placeholder", "dummy", "text", "filler"],
  },
  {
    slug: "colour-converter",
    name: "Colour Converter",
    description: "Convert colours between HEX, RGB, and HSL formats instantly.",
    icon: Palette,
    category: "Design",
    keywords: ["colour", "color", "hex", "rgb", "hsl", "convert", "picker"],
  },
  {
    slug: "case-converter",
    name: "Case Converter",
    description: "Convert text between UPPER, lower, Title, camelCase, snake_case and more.",
    icon: CaseSensitive,
    category: "Text",
    keywords: ["case", "upper", "lower", "title", "camel", "snake", "kebab", "pascal"],
  },
  {
    slug: "markdown-to-html",
    name: "Markdown to HTML",
    description: "Convert Markdown text to clean HTML with live preview.",
    icon: FileCode,
    category: "Developer",
    keywords: ["markdown", "html", "convert", "render", "preview", "md"],
  },
  {
    slug: "password-generator",
    name: "Password Generator",
    description: "Generate strong, cryptographically secure random passwords.",
    icon: KeyRound,
    category: "Security",
    keywords: ["password", "generate", "random", "strong", "secure", "crypto"],
  },
  {
    slug: "uuid-generator",
    name: "UUID Generator",
    description: "Generate unique UUIDs (v4) with one click. Bulk generate supported.",
    icon: Fingerprint,
    category: "Developer",
    keywords: ["uuid", "guid", "generate", "unique", "identifier", "v4"],
  },
  {
    slug: "timestamp-converter",
    name: "Unix Timestamp Converter",
    description: "Convert between Unix timestamps and human-readable dates.",
    icon: Clock,
    category: "Developer",
    keywords: ["unix", "timestamp", "epoch", "date", "time", "convert"],
  },
  {
    slug: "css-minifier",
    name: "CSS Minifier",
    description: "Minify CSS to reduce file size. Remove comments and whitespace.",
    icon: Minimize2,
    category: "Developer",
    keywords: ["css", "minify", "compress", "optimize", "reduce", "whitespace"],
  },
  {
    slug: "html-entities",
    name: "HTML Entity Encoder",
    description: "Encode special characters to HTML entities or decode them back.",
    icon: Code2,
    category: "Encoding",
    keywords: ["html", "entity", "encode", "decode", "special", "characters", "escape"],
  },
  {
    slug: "qr-code",
    name: "QR Code Generator",
    description: "Generate QR codes from any text, URL or data. Download as PNG.",
    icon: QrCode,
    category: "Utility",
    keywords: ["qr", "code", "generate", "barcode", "scan", "url"],
  },
  {
    slug: "hash-generator",
    name: "Hash Generator",
    description: "Generate SHA-256, SHA-1 and MD5 hashes from any text input.",
    icon: Hash,
    category: "Security",
    keywords: ["hash", "sha", "md5", "sha256", "sha1", "checksum", "digest"],
  },
  {
    slug: "image-resizer",
    name: "Image Resizer",
    description: "Resize images for Instagram, Twitter, Facebook, YouTube and more with one click.",
    icon: ImageIcon,
    category: "Image",
    keywords: ["image", "resize", "crop", "social media", "instagram", "facebook", "twitter", "youtube", "photo"],
  },
  {
    slug: "instagram-fonts",
    name: "Instagram Font Generator",
    description: "Generate stylish Unicode fonts for Instagram bios, captions, tweets and more.",
    icon: Type,
    category: "Social Media",
    keywords: ["instagram", "font", "fancy", "text", "unicode", "bio", "caption", "twitter", "tiktok", "cursive"],
  },
  {
    slug: "mortgage-calculator",
    name: "Mortgage Calculator",
    description: "Calculate UK mortgage repayments, stamp duty, and total costs instantly.",
    icon: PoundSterling,
    category: "Finance",
    keywords: ["mortgage", "calculator", "uk", "stamp duty", "repayment", "interest", "house", "property"],
  },
  {
    slug: "invoice-generator",
    name: "Invoice Generator",
    description: "Create beautiful professional invoices with live preview. Add your logo, customise colours, download as PDF.",
    icon: Receipt,
    category: "Finance",
    keywords: ["invoice", "bill", "receipt", "pdf", "generator", "business", "freelance", "payment"],
  },
  {
    slug: "colour-palette",
    name: "Colour Palette Generator",
    description: "Generate beautiful colour palettes. Lock colours, export as CSS, Tailwind or SCSS.",
    icon: Pipette,
    category: "Design",
    keywords: ["colour", "color", "palette", "generator", "css", "tailwind", "design", "scheme", "harmonious"],
  },
];

export const categories = [...new Set(tools.map((t) => t.category))];
